# Generated by Django 3.1.3 on 2021-02-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedembed',
            name='author_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='savedembed',
            name='provider_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='savedembed',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='savedembed',
            name='type',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
