# Generated by Django 3.1.3 on 2021-02-07 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210207_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedembed',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
